### ISSUE TITLE
Check mongo for injection and stuff

### ISSUE THREAD

**Issue by gazdagergo** [Code-for-Hungary/tisztaszavazas-api#3]
https://github.com/layro01/node-api-goat/blob/master/app/server.js

Prototype pollution
- https://portswigger.net/daily-swig/prototype-pollution-the-dangerous-and-underrated-vulnerability-impacting-javascript-applications

**Comment by Peneheals** [comment]
With d048fe368a0d44550ff80f073ad79cf285e14585 in #9 we are not writing to the db (it will be optionally in the future), so I close this issue.

**Comment by gazdagergo** [comment]
3ee8fa354461fae836179925b8e63b223c2baac9 makes it optional
